### ISSUE TITLE
TypeError: f.getClientRects is not a function. (In 'f.getClientRects()', 'f.getClientRects' is undefined)

### ISSUE THREAD

**Issue by hambern** [markdalgleish/stellar.js#145]
I keep getting: TypeError: f.getClientRects is not a function. (In 'f.getClientRects()', 'f.getClientRects' is undefined) though I think I've tried everything. I've included both jquery and stellar.js through bower and I use them on the page:

From Bower:
~~~
"jquery.stellar": "^0.6.2",
"jquery": "^3.1.1"
~~~

The js:
~~~script
$(function() {
  $.stellar();
});
~~~

The html
~~~html
<div class="jumbotron stellar-background" data-stellar-background-ratio="0.5" style="background-image: url('extend/theme/front/img/bg-blur.jpg')">
    <div class="centered container">
      <div class="text-center">
        <h1>Bla bla</h1>
      </div>
    </div>
  </div>
~~~

The css
~~~css
.stellar-background {
  position: relative;
  background-size: cover;
  background-attachment: fixed;
  background-position: 50% 0;
  background-repeat: no-repeat;
}
~~~

**Comment by mgsmus** [comment]
You need jQuery Migrate 3.0
http://code.jquery.com/jquery-migrate-3.0.0.js

**Comment by samuelbsp** [comment]
So.. It's not working with jquery 3.0 ? Is there gonna be a fix for that ? I don't want to use jQuery Migrate just for stellar...

**Comment by mgsmus** [comment]
I created a pull request for the fix https://github.com/markdalgleish/stellar.js/pull/147

**Comment by Uranbold** [comment]
@mgsmus Your Pull for Fix has failed?

It seems not fixed on main version.

**Comment by mgsmus** [comment]
I don't understand that Travis-CI yet. 
I did not have a chance to look at it in detail tho

**Comment by LucasSodre** [comment]
I want to run a program that uses jquery-ui-1.10.4 and have jquery 3.1.1 on my webpage, it gives the error "Uncaught TypeError: f.getClientRects is not a function". I have already tried using jquery-migrate-3.0.0.js on my page but did not change the error.

**Comment by angelotupaz** [comment]
**_lkjkljkl_**

**Comment by ahkui** [comment]
you can use this version and have pull request at #158 
`
npm install --save stellar.js
`

**Comment by TemaSM** [comment]
@markdalgleish How about to finally merge PR provided by @ahkui and give him rights to be a project collaborator?
